import type { ChatInputCommandInteraction } from 'discord.js'
import { ApplicationCommandOptionType, EmbedBuilder } from 'discord.js'
import type { MySuperClient } from '../../index'

export default {
  name: 'poll',
  description: 'Create your own poll!',
  options: [
    {
      name: 'title',
      description: 'Write your poll title',
      type: ApplicationCommandOptionType.String,
      required: true,
    },
    {
      name: 'question',
      description: 'Write your poll question',
      type: ApplicationCommandOptionType.String,
      required: true,
    },
  ],
  async run(client: MySuperClient, interaction: ChatInputCommandInteraction) {
    const pollTitle = interaction.options.getString('title')!
    const pollQuestion = interaction.options.getString('question')!

    const embed = new EmbedBuilder()
      .setTitle(pollTitle)
      .setColor('#00a3b5')
      .setDescription(pollQuestion)
      .setTimestamp()
      .setFooter({ text: `New poll generated by ${interaction.user.tag}` })

    const poll = await interaction.reply({ embeds: [embed], fetchReply: true })

    poll.react('✅')
    poll.react('❌')
  },
}
